language: python
notifications:
  email: false
python:
    - "3.7"
    - "3.8"
script:
  - git config user.name "Kyle Barron";
  - git config user.email "kylebarron2@gmail.com";
  - git remote add gh-token "https://kylebarron:${GITHUB_TOKEN}@github.com/kylebarron/landsat-cogeo-mosaic.git";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - pip install -IU -r '.docs';
  - mkdocs gh-deploy -v --clean --remote-name gh-token -b gh-pages --force;
